### ISSUE TITLE
Java 7 support

### ISSUE THREAD

**Issue by StevenOAG** [LitleCo/litle-sdk-for-java#41]
If you run the functional test suite using JDK7, most of the tests fail due to a javax.net.ssl.SSLPeerUnverifiedException because JDK7 has TLS1.1 and TLS1.2 disabled by default.  For those clients that are stuck on Java 7, this presents a problem since the SDK does not expose anyway to force TLS1.1+ in the Apache HttpClient library.

**Comment by amitvig22** [comment]
Yes that is true 

You could try adding something like the following to your startup script, assuming Java 1.7:

JAVACMD="$JAVACMD -Ddeployment.security.SSLv2Hello=false -Ddeployment.security.SSLv3=false -Ddeployment.security.TLSv1=false -D\
deployment.security.TLSv1.1=true -Ddeployment.security.TLSv1.2=true"

**Comment by StevenOAG** [comment]
That doesn't fix the problem:
![image](https://cloud.githubusercontent.com/assets/4664553/9945801/2115fb52-5d55-11e5-9cf8-392e3cc7db6d.png)

**Comment by amitvig22** [comment]
if you hava a Java control panel, try setting it there as well.

**Comment by StevenOAG** [comment]
#1 My example is from an IDE which is using a JDK.  The JDK doesn't come with the java.cpl.exe file unless you go to the jre subfolder which did not fix it
#2 The environments that this will run in are headless so the control panel doesn't apply

This blog post that I found sums up what I have experienced so far: http://fsanglier.blogspot.com/2015/04/java-7-and-tlsv12-supported-but-not-enabled.html.  If you dig down into the HttpClient sources, you will see that the default behavior is to create an SSLSocketFactory that does NOT factor in system properties.  The way to override this to to provide a SchemeRegistry with a custom SocketFactory, and then pass that into a ClientConnectionManager which is then used to create a HttpClient.
