### ISSUE TITLE
Upgrade Litle SDK from 9.10.0 to 9.12.2 throwing NullPointerException

### ISSUE THREAD

**Issue by elangops** [LitleCo/litle-sdk-for-java#51]
Exception in thread "main" java.lang.NullPointerException
at com.litle.sdk.Communication.requestToServer(Communication.java:130)
at com.litle.sdk.LitleOnline.sendToLitle(LitleOnline.java:706)
at com.litle.sdk.LitleOnline.authorize(LitleOnline.java:165)
at com.litle.sdk.LitleOnline.authorize(LitleOnline.java:157)
at com.jtv.vantiv.AuthExample.main(AuthExample.java:91)

**Comment by brianarnold789** [comment]
Hi,
Are you having this problem with all the samples or just the AuthExample?

**Comment by elangops** [comment]
My payment code works fine with 9.10.0. I tried my code and AuthExample in version both are having same issue

**Comment by elangops** [comment]
I tried AuthExample only in 9.12.2 version.

**Comment by brianarnold789** [comment]
I am trying to reproduce this error, which version of Java are you using on which OS?

**Comment by elangops** [comment]
Java 1.8 and line os

**Comment by brianarnold789** [comment]
There is a difference between Java 7 and 8 in terms of HTTP protocols that was allowing out test environment (Java 7) to work correctly but fail in Java 8. I have update the relevant code and am running tests in both Java environments. After successful testing I will update the releases to have the corrected code.

**Comment by brianarnold789** [comment]
updated release after testing for Java 7 & 8, can you try the new jar to see if it works for your environment?

**Comment by elangops** [comment]
Issue fixed.

Thank you.
