### ISSUE TITLE
usage of BasicHttpClientConnectionManager in Communication/LitleOnline

### ISSUE THREAD

**Issue by elucash** [LitleCo/litle-sdk-for-java#55]
Currently, `BasicHttpClientConnectionManager` is used in `Communication` class.  `BasicHttpClientConnectionManager` is documented to properly work only with a single thread. Using `LitleOnline` object with multiple threads sending transactions is causing IllegalStateException "Connection is still allocated".

Please advise if there are specific rules how to correctly use `LitleOnline` class in multi-threaded environment (link to some docs etc). Can it be used from multiple threads? If otherwise, `Communication` and `LitleOnline` classes are thread-safe, can `BasicHttpClientConnectionManager` be potentially replaced by the alternative, multithreading-capable connection manager, like `PoolingHttpClientConnectionManager` ?
Thank you!

**Comment by brianarnold789** [comment]
Hi @elucash ,
You are correct, the `LitleOnline` is not thread-safe. In a multi-threaded environment a pool of `LitleOnline`s can be created and your multi-threaded app would draw from that pool. We had considered using a pooled connection manager in the `Communication` class but the number of options makes it a difficult task to provide the simplicity we are striving for while still allowing more sophisticated  systems to have access to "all the knobs", so to speak. We would be happy to discuss this further if you feel it's warranted, sdksupport@vantiv.com may be the best avenue for that discussion.

**Comment by elucash** [comment]
@brianarnold789 Thank you for explanation! It's ok for us to implement pooling as it was already discussed as a possible workaround. Of course, there's a little benefit of complicating the client to provide extra guarantees in the current circumstances. We will contact support if will face other issues.
