### ISSUE TITLE
Transaction amount [33333.04] exceeded limit of [12000.00]

### ISSUE THREAD

**Issue by shradable** [LitleCo/litle-sdk-for-java#56]
We are getting exception:
Transaction amount [33333.04] exceeded limit of [12000.00]. at com.litle.sdk.LitleOnline.sendToLitle(LitleOnline.java:714)

We are getting this error only when we get response code as "1" from Vantiv as per the code in LitleOnline.java in 9.10 version of LitleSdk.
if("1".equals(response.getResponse())) {
	throw new LitleOnlineException(response.getMessage());
}

Can someone please tell me the cause of this error?

**Comment by davekartik24** [comment]
The error is because of the amount you are passing in the request is greater than the allowed amount in your profile as indicated by the exception "Transaction amount [33333.04] exceeded limit of [12000.00]". 
If you want to change your profile please contact implementation team(Implementation@vantiv.com)

**Comment by shradable** [comment]
Hi Kartik, thanks for your reply. But we are getting this error only for ARS, MXN and CLP currencies for different merchants.
Can you please tell me if currency is considered while comparing the amount with its allowed limit?

**Comment by swapnilhande** [comment]
Hi,

The SDK is handling the error response correctly as received by showing the error message and cause. To know on why you are getting this error on only certain currency codes, please contact customer care at ecc@vantiv.com as they are best equipped to check your profile and see any configuration that might cause this.

Thank you.
